#!/usr/bin/env bash
# will display information about subdomains.
domain=$1
subdomains="www lb-01 web-01 web-02"

function show_info() {
    for sub in $subdomains; do
        echo -n "The subdomain $sub is a "
        dig "$sub"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4 " record and points to " $5}'
    done
}

if [ "$#" == 2 ]; then
    echo -n "The subdomain $2 is a "
    dig "$2"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4 " record and points to " $5}'
else
    show_info
fi
