#!/usr/bin/env bash
# will display information about SUBDS.
SUBS="www lb-01 web-01 web-02"
show_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
  for sub in $SUBS; do
    show_info "$1" "$sub"
  done
elif [ "$#" == 2 ]; then
  show_info "$1" "$2"
fi
