#!/usr/bin/env bash
# install nginx on a server.
# Requirements:
# - Nginx should be listening on port 80
# - it must return a page that contains the string Holberton School
# - can’t use systemctl for restarting nginx

apt-get -y update
sudo apt-get -y upgrade
apt-get -y install nginx

sudo /usr/sbin/service nginx restart

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
