#!/usr/bin/env bash
# install nginx on a server.
# Requirements:
# - Nginx should be listening on port 80
# - it must return a page that contains the string Holberton School
# - can’t use systemctl for restarting nginx

apt-get update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sudo service nginx restart
