#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo /usr/sbin/service nginx start
string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i $string" /etc/nginx/sites-available/default
sudo /usr/sbin/service nginx restart
