#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string
# Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo /usr/sbin/service nginx start
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-enabled/default
sudo /usr/sbin/service nginx restart
