#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string
# Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo /usr/sbin/service nginx start
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
string="/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}" 
sudo sed -i '$string' /etc/nginx/sites-enabled/default
sudo /usr/sbin/service nginx restart
