#!/usr/bin/env bash
# add a custom Nginx response header
# Configure Nginx so that its HTTP response contains a custom header
# (on web-01 and web-02

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo touch /var/www/html/custom_404.html
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        return 301 https://www.holbertonschool.com/;
    }
    error_page 404 /custom_404.html;
    location = /custom_404.html {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo /usr/sbin/service nginx restart
