#!/usr/bin/env bash
# Configure HAproxy with version equal or greater than 1.5 so that it send
# traffic to web-01 and web-02

sudo apt-get -y update
sudo apt-get install -y haproxy=1.6.*

printf %s "
frontend http_front
    bind *:80
    mode http
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 35.229.34.27 check
    server web-02 35.237.166.174 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
