#!/usr/bin/env bash
# fizzbuzz
for i in {1..100}; do
    if ((i>1)); then
        printf "\n"
    fi
    if ((i % 3 == 0)); then
        printf "Fizz"
        if ((i % 5 == 0)); then
            printf "Buzz"
        fi
    elif ((i % 5 == 0)); then
        printf "Buzz"
    else
        printf '%s' "$i"
    fi
done
printf "\n"