#!/usr/bin/env bash
# Read /etc/passwd file and displays info.
while IFS=":" read -r s1 s2 s3 s4 s5 s6 s7; do
    echo "The user $s1 is part of the $s4 gang, lives in $s6 and rides $s7. $s3's place is protected by the passcode $s2, more info about the user here: $s5"
done < "/etc/passwd"